# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Memeolist' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Memeolist
  pod "Kingfisher" 
  pod "Alamofire"
  
  if ENV['LOCAL_DIR']
      pod 'AGSCore', :path => ENV['LOCAL_DIR']
      pod 'AGSAuth', :path => ENV['LOCAL_DIR']
      pod 'AGSSync', :path => ENV['LOCAL_DIR']
  else
      pod 'AGSCore', :git => 'https://github.com/aerogear/aerogear-ios-sdk'
      pod 'AGSAuth', :git => 'https://github.com/aerogear/aerogear-ios-sdk'
      pod 'AGSSync', :git => 'https://github.com/aerogear/aerogear-ios-sdk'
  end
  
  ## Helpers
  pod 'UIImageCropper'
  pod 'IQKeyboardManagerSwift'
  
  target 'MemeolistTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
